# '.' is the stop codon
DNA_Codons = {
    "AAA": "K", "AAG": "K",
    "AAC": "N", "AAT": "N",
    "ACA": "T", "ACC": "T", "ACG": "T", "ACT": "T",
    "AGA": "R", "AGG": "R", "CGA": "R", "CGC": "R", "CGG": "R", "CGT": "R",
    "AGC": "S", "AGT": "S", "TCA": "S", "TCC": "S", "TCG": "S", "TCT": "S",
    "ATA": "I", "ATC": "I", "ATT": "I",
    "ATG": "M",
    "CAA": "Q", "CAG": "Q",
    "CAC": "H", "CAT": "H",
    "CCA": "P", "CCC": "P", "CCG": "P", "CCT": "P",
    "CTA": "L", "CTC": "L", "CTG": "L", "CTT": "L", "TTA": "L", "TTG": "L",
    "GAA": "E", "GAG": "E",
    "GAC": "D", "GAT": "D",
    "GCA": "A", "GCC": "A", "GCG": "A", "GCT": "A",
    "GGA": "G", "GGC": "G", "GGG": "G", "GGT": "G",
    "GTA": "V", "GTC": "V", "GTG": "V", "GTT": "V",
    "TAA": ".", "TAG": ".", "TGA": ".",
    "TAC": "Y", "TAT": "Y",
    "TGC": "C", "TGT": "C",
    "TGG": "W",
    "TTC": "F", "TTT": "F",
}

RNA_Codons = {
    "AAA": "K", "AAG": "K",
    "AAC": "N", "AAU": "N",
    "ACA": "T", "ACC": "T", "ACG": "T", "ACU": "T",
    "AGA": "R", "AGG": "R", "CGA": "R", "CGC": "R", "CGG": "R", "CGU": "R",
    "AGC": "S", "AGU": "S", "UCA": "S", "UCC": "S", "UCG": "S", "UCU": "S",
    "AUA": "I", "AUC": "I", "AUU": "I",
    "AUG": "M",
    "CAA": "Q", "CAG": "Q",
    "CAC": "H", "CAU": "H",
    "CCA": "P", "CCC": "P", "CCG": "P", "CCU": "P",
    "CUA": "L", "CUC": "L", "CUG": "L", "CUU": "L", "UUA": "L", "UUG": "L",
    "GAA": "E", "GAG": "E",
    "GAC": "D", "GAU": "D",
    "GCA": "A", "GCC": "A", "GCG": "A", "GCU": "A",
    "GGA": "G", "GGC": "G", "GGG": "G", "GGU": "G",
    "GUA": "V", "GUC": "V", "GUG": "V", "GUU": "V",
    "UAA": ".", "UAG": ".", "UGA": ".",
    "UAC": "Y", "UAU": "Y",
    "UGC": "C", "UGU": "C",
    "UGG": "W",
    "UUC": "F", "UUU": "F",
}